### ISSUE TITLE
Post Image Size

### ISSUE THREAD

**Issue by seaniopsyc** [dencold/hasper#32]
Is there a way to control the image size for each post header (banner)? Currently, the rendered image is zoomed in and cuts off much of the image.

**Comment by dencold** [comment]
Hi @seaniopsyc, this is not currently configurable, and probably never will be. I want the banner to be 100% of the width of whatever the device's viewport, then we use the css `vh` property to scale the height appropriately. This makes the banner responsive to any device the user decides to view the site with. If you have to start setting individual dimensions for each of you banners, it could get ugly pretty quickly.

Let me know if you have any better ideas for how to handle this.

Thanks for using the theme!

**Comment by dencold** [comment]
Hi @seaniopsyc, let me know if this helps to answer your question. I will close this issue tomorrow. Thanks!

**Comment by dencold** [comment]
Closing this. Hope you are all set on your end.

**Comment by seaniopsyc** [comment]
Yes, thanks. Apologies for my delayed reply.
